const events = [
    {
        id: 1,
        type: "custom",
        image:
            "https://hiu.vn/wp-content/uploads/2023/02/z4079030922121_5c7c9db54a32aeca0315e93b99e23e2e-1-2-2-870x285.jpg",
        title: "Cuộc thi Tìm hiểu 93 năm Lịch sử Đảng Cộng sản VN",
        time: "2025-06-10 09:00",
        location: "HIU, TP.HCM",
        description:
            "Kỷ niệm 93 năm thành lập Đảng, nâng cao nhận thức. Tăng 3 ĐRL tiêu chí 1.",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "cuộc thi", "đrl"],
        drlCriteria: 1,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 2,
        type: "custom",
        image: "https://hiu.vn/wp-content/uploads/2023/03/DSC03048-800x285.jpg",
        title: "Giao lưu cùng các Sếp - Cơ hội cho ai",
        time: "2025-06-15 14:00",
        location: "HIU, TP.HCM",
        description:
            "Gặp gỡ các Sếp lớn, học hỏi kinh nghiệm. Tăng 2 ĐRL tiêu chí 2.",
        eventType: "Talkshow",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/sinh-vien-hiu-hao-hung-giao-luu-cung-cac-sep/",
        tags: ["học tập", "kỹ năng", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 3,
        type: "custom",
        image: "https://hiu.vn/wp-content/uploads/2022/12/thumnail-800x285.jpg",
        title: "Hội nghị Khoa học – Công nghệ HIU",
        time: "2025-06-20 08:00",
        location: "HIU, TP.HCM",
        description: "Báo cáo khoa học, kỷ niệm 25 năm HIU. Tăng 3 ĐRL tiêu chí 3.",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/chuong-trinh-hoi-nghi-khoa-hoc-cong-nghe-hiu-mo-rong/",
        tags: ["học tập", "cntt", "đrl"],
        drlCriteria: 3,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 4,
        type: "custom",
        image:
            "https://hiu.vn/wp-content/uploads/2025/05/thum-ngay-hoi-quoc-te-dieu-duong-hiu-2025-800x285.jpg",
        title: "Ngày Quốc tế Điều dưỡng 2025",
        time: "2025-06-25 09:00",
        location: "Hội trường Beethoven, HIU",
        description:
            "Tôn vinh điều dưỡng, tiếp lửa Florence. Tăng 3 ĐRL tiêu chí 4.",
        eventType: "Hoạt động đoàn thể",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/ngay-quoc-te-dieu-duong-2025-sinh-vien-hiu-tiep-lua-florence-nightingale/",
        tags: ["thiện nguyện", "đrl"],
        drlCriteria: 4,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 5,
        type: "custom",
        image: "https://hiu.vn/wp-content/uploads/2024/12/2-870x285.jpg",
        title: "Chung kết Olympic Tiếng Anh 2024",
        time: "2025-07-01 09:00",
        location: "Hội trường Beethoven, HIU",
        description: "Cuộc thi Tiếng Anh gay cấn. Tăng 4 ĐRL tiêu chí 2.",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/chuc-mung-vong-chung-ket-olympic-tieng-anh-2024-da-thanh-cong-ruc-ro/",
        tags: ["học tập", "cuộc thi", "đrl"],
        drlCriteria: 2,
        drlPoints: 4,
        hasSeating: true
    },
    {
        id: 6,
        type: "custom",
        image: "https://hiu.vn/wp-content/uploads/2024/10/SSS-870x285.jpg",
        title: "Talkshow Sức khỏe Tinh thần",
        time: "2025-07-05 14:00",
        location: "HIU, TP.HCM",
        description: "Nâng cao sức khỏe tinh thần. Tăng 3 ĐRL tiêu chí 2.",
        eventType: "Talkshow",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/talkshow-nang-cao-suc-khoe-tinh-than-cho-sinh-vien-voi-thong-diep-khong-on-cung-khong-sao/",
        tags: ["học tập", "kỹ năng", "đrl"],
        drlCriteria: 2,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 7,
        type: "custom",
        image: "https://hiu.vn/wp-content/uploads/2024/09/VS110-800x285.jpg",
        title: "Hướng dẫn viên Du lịch Triển vọng 2024",
        time: "2025-07-10 09:00",
        location: "HIU, TP.HCM",
        description: "Cọ xát thực tế ngành Du lịch. Tăng 3 ĐRL tiêu chí 2.",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/hiu-dong-to-chuc-huong-dan-vien-du-lich-trien-vong-toan-thanh-2024/",
        tags: ["học tập", "cuộc thi", "đrl"],
        drlCriteria: 2,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 8,
        type: "custom",
        image:
            "https://hiu.vn/wp-content/uploads/2024/06/447729001_424865507120950_2290725292462772115_n-870x285.jpg",
        title: "Tọa đàm Nghệ thuật Cải lương",
        time: "2025-07-15 17:00",
        location: "Hội trường Beethoven, HIU",
        description: "Khám phá âm nhạc dân tộc. Tăng 2 ĐRL tiêu chí 2.",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/toa-dam-tim-hieu-am-nhac-dan-toc-hoc-duong-nghe-thuat-cai-luong-am-vang-hon-viet/",
        tags: ["giải trí", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 9,
        type: "custom",
        image: "https://hiu.vn/wp-content/uploads/2024/04/2-2-640x285.jpg",
        title: "Gala Talent Generation 2024",
        time: "2025-07-20 18:00",
        location: "HIU, TP.HCM",
        description: "Bùng nổ tài năng sinh viên. Tăng 2 ĐRL tiêu chí 2.",
        eventType: "Festival",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/san-sang-bung-no-cho-dem-gala-talent-generation-2024/",
        tags: ["giải trí", "festival", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 10,
        type: "custom",
        image:
            "https://hiu.vn/wp-content/uploads/2024/03/z5244900136193_31f8d00b8d1b713686b6955bfb7bd85b-800x285.jpg",
        title: "Rung Chuông Vàng 2024",
        time: "2025-07-25 09:00",
        location: "HIU, TP.HCM",
        description: "Tìm hiểu văn hóa Hàn Quốc. Tăng 4 ĐRL tiêu chí 2.",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/nhanh-tay-dang-ky-cuoc-thi-rung-chuong-vang/",
        tags: ["học tập", "cuộc thi", "đrl"],
        drlCriteria: 2,
        drlPoints: 4,
        hasSeating: true
    },
    {
        id: 11,
        type: "custom",
        image: "https://hiu.vn/wp-content/uploads/2024/03/3-1-526x285.jpg",
        title: "King & Queen 2024",
        time: "2025-08-01 18:00",
        location: "HIU, TP.HCM",
        description: "Thử độ ăn ý cặp đôi. Tăng 2 ĐRL tiêu chí 2.",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/king-queen-chinh-thuc-quay-tro-lai/",
        tags: ["giải trí", "cuộc thi", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 12,
        type: "custom",
        image:
            "https://hiu.vn/wp-content/uploads/2024/03/rung-chuong-vang_07-03-2024-822x285.jpg",
        title: "Rung Chuông Vàng Hàn Quốc",
        time: "2025-08-05 09:00",
        location: "HIU, TP.HCM",
        description: "Tìm hiểu tỉnh Jeonlanam-do. Tăng 4 ĐRL tiêu chí 2.",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl: "https://hiu.vn/hiu-student-center/cuoc-thi-rung-chuong-vang/",
        tags: ["học tập", "cuộc thi", "đrl"],
        drlCriteria: 2,
        drlPoints: 4,
        hasSeating: true
    },
    {
        id: 13,
        type: "custom",
        image:
            "https://hiu.vn/wp-content/uploads/2023/06/Thie%CC%82%CC%81t-ke%CC%82%CC%81-kho%CC%82ng-te%CC%82n-10-800x285.png",
        title: "Chung kết HIU Logistics Talent 2023",
        time: "2025-08-10 14:00",
        location: "HIU, TP.HCM",
        description: "Tranh tài logistics. Tăng 4 ĐRL tiêu chí 3.",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/top-6-doi-thi-tai-vong-chung-ket-cuoc-thi-hiu-logistics-talent-2023/",
        tags: ["học tập", "cuộc thi", "đrl"],
        drlCriteria: 3,
        drlPoints: 4,
        hasSeating: true
    },
    {
        id: 14,
        type: "custom",
        image: "https://hiu.vn/wp-content/uploads/2023/05/DSC00392-800x285.jpg",
        title: "HIU Startup 2023: Bột mặt nạ AraFace",
        time: "2025-08-15 18:00",
        location: "Hội trường Beethoven, HIU",
        description: "Chung kết khởi nghiệp. Tăng 5 ĐRL tiêu chí 3.",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/du-an-bot-mat-na-araface-cua-dndn-gianh-chien-thang-tai-hiu-startup-2023/",
        tags: ["học tập", "cuộc thi", "khởi nghiệp", "đrl"],
        drlCriteria: 3,
        drlPoints: 5,
        hasSeating: true
    },
    {
        id: 15,
        type: "custom",
        image:
            "https://hiu.vn/wp-content/uploads/2023/05/Thie%CC%82%CC%81t-ke%CC%82%CC%81-kho%CC%82ng-te%CC%82n-8-800x285.png",
        title: "Olympic Tiếng Anh Ngôn ngữ Anh",
        time: "2025-08-20 09:00",
        location: "HIU, TP.HCM",
        description: "Thi đấu Tiếng Anh. Tăng 4 ĐRL tiêu chí 2.",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl:
            "https://hiu.vn/hiu-student-center/nhung-khoanh-khac-an-tuong-cua-sinh-vien-nganh-ngon-ngu-anh-hiu-tai-cuoc-thi-olympic-tieng-anh/",
        tags: ["học tập", "cuộc thi", "đrl"],
        drlCriteria: 2,
        drlPoints: 4,
        hasSeating: true
    },
    {
        id: 16,
        type: "custom",
        image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655",
        title: "Hội thảo Hướng dẫn Học bổng Du học",
        time: "2025-08-25 14:00",
        location: "HIU, TP.HCM",
        description:
            "Tìm hiểu cách săn học bổng quốc tế. Tăng 3 ĐRL tiêu chí 1. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "học bổng", "đrl"],
        drlCriteria: 1,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 17,
        type: "custom",
        image: "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f",
        title: "Cuộc thi Học bổng Lãnh đạo Trẻ",
        time: "2025-09-01 09:00",
        location: "HIU, TP.HCM",
        description:
            "Giành học bổng 50 triệu đồng. Tăng 5 ĐRL tiêu chí 2. Tham gia ngay!",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "học bổng", "cuộc thi", "đrl"],
        drlCriteria: 2,
        drlPoints: 5,
        hasSeating: true
    },
    {
        id: 18,
        type: "custom",
        image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655",
        title: "Tư vấn Học bổng ASEAN",
        time: "2025-09-05 15:00",
        location: "Online",
        description:
            "Khám phá học bổng ASEAN. Tăng 3 ĐRL tiêu chí 1. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "học bổng", "đrl"],
        drlCriteria: 1,
        drlPoints: 3,
        hasSeating: false
    },
    {
        id: 19,
        type: "custom",
        image: "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f",
        title: "Cuộc thi Ý tưởng Học bổng Khởi nghiệp",
        time: "2025-09-10 08:00",
        location: "HIU, TP.HCM",
        description: "Trình bày ý tưởng, giành học bổng. Tăng 5 ĐRL tiêu chí 3.",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "học bổng", "cuộc thi", "khởi nghiệp", "đrl"],
        drlCriteria: 3,
        drlPoints: 5,
        hasSeating: true
    },
    {
        id: 20,
        type: "custom",
        image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655",
        title: "Hội thảo Học bổng Chevening",
        time: "2025-09-15 14:00",
        location: "HIU, TP.HCM",
        description:
            "Tìm hiểu học bổng Chevening. Tăng 3 ĐRL tiêu chí 1. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "học bổng", "đrl"],
        drlCriteria: 1,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 21,
        type: "custom",
        image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1",
        title: "Chiếu phim Interstellar",
        time: "2025-09-20 18:00",
        location: "Hội trường Beethoven, HIU",
        description: "Thưởng thức khoa học viễn tưởng. Tăng 2 ĐRL tiêu chí 2.",
        eventType: "Chiếu phim",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "phim", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 22,
        type: "custom",
        image: "https://images.unsplash.com/photo-1531251445707-1f000e98d7ea",
        title: "Chiếu phim The Dark Knight",
        time: "2025-09-25 19:00",
        location: "Hội trường HIU",
        description: "Bom tấn hành động. Tăng 2 ĐRL tiêu chí 2. Đăng ký ngay!",
        eventType: "Chiếu phim",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "phim", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 23,
        type: "custom",
        image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1",
        title: "Chiếu phim Inception",
        time: "2025-10-01 18:00",
        location: "Hội trường HIU",
        description: "Khám phá giấc mơ. Tăng 2 ĐRL tiêu chí 2. Đừng bỏ lỡ!",
        eventType: "Chiếu phim",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "phim", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 24,
        type: "custom",
        image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1",
        title: "Chiếu phim Dune: Part Two",
        time: "2025-10-05 18:00",
        location: "Hội trường HIU",
        description: "Bom tấn khoa học viễn tưởng. Tăng 2 ĐRL tiêu chí 2.",
        eventType: "Chiếu phim",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "phim", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 25,
        type: "custom",
        image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1",
        title: "Chiếu phim Mad Max: Fury Road",
        time: "2025-10-10 19:00",
        location: "Hội trường HIU",
        description: "Hành động đỉnh cao. Tăng 2 ĐRL tiêu chí 2. Đăng ký ngay!",
        eventType: "Chiếu phim",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "phim", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 26,
        type: "custom",
        image: "https://images.unsplash.com/photo-1502224562085-639556652f33",
        title: "Chạy bộ Từ thiện HIU",
        time: "2025-10-15 07:00",
        location: "Công viên Tao Đàn, TP.HCM",
        description: "Gây quỹ cho trẻ em khó khăn. Tăng 5 ĐRL tiêu chí 4.",
        eventType: "Thiện nguyện",
        audience: "Cộng đồng",
        readMoreUrl: "#",
        tags: ["thiện nguyện", "đrl", "hoạt động xã hội"],
        drlCriteria: 4,
        drlPoints: 5,
        hasSeating: false
    },
    {
        id: 27,
        type: "custom",
        image: "https://images.unsplash.com/photo-1576765607924-3a7bd1c73d84",
        title: "Ngày Hội Hiến máu HIU",
        time: "2025-10-20 08:00",
        location: "HIU, TP.HCM",
        description: "Hiến máu cứu người. Tăng 4 ĐRL tiêu chí 4. Tham gia ngay!",
        eventType: "Thiện nguyện",
        audience: "Cộng đồng",
        readMoreUrl: "#",
        tags: ["thiện nguyện", "đrl", "hoạt động xã hội"],
        drlCriteria: 4,
        drlPoints: 4,
        hasSeating: false
    },
    {
        id: 28,
        type: "custom",
        image: "https://images.unsplash.com/photo-1502224562085-639556652f33",
        title: "Ngày Hội Môi trường Xanh",
        time: "2025-10-25 09:00",
        location: "HIU, TP.HCM",
        description: "Trồng cây, bảo vệ môi trường. Tăng 4 ĐRL tiêu chí 4.",
        eventType: "Thiện nguyện",
        audience: "Cộng đồng",
        readMoreUrl: "#",
        tags: ["thiện nguyện", "đrl", "hoạt động xã hội"],
        drlCriteria: 4,
        drlPoints: 4,
        hasSeating: false
    },
    {
        id: 29,
        type: "custom",
        image: "https://images.unsplash.com/photo-1502224562085-639556652f33",
        title: "Chiến dịch Dọn rác Biển",
        time: "2025-11-01 07:00",
        location: "Bãi biển Vũng Tàu",
        description: "Làm sạch bãi biển. Tăng 5 ĐRL tiêu chí 4. Tham gia ngay!",
        eventType: "Thiện nguyện",
        audience: "Cộng đồng",
        readMoreUrl: "#",
        tags: ["thiện nguyện", "đrl", "hoạt động xã hội"],
        drlCriteria: 4,
        drlPoints: 5,
        hasSeating: false
    },
    {
        id: 30,
        type: "custom",
        image: "https://images.unsplash.com/photo-1576765607924-3a7bd1c73d84",
        title: "Ngày Hội Tình nguyện HIU",
        time: "2025-11-05 08:00",
        location: "HIU, TP.HCM",
        description: "Hoạt động tình nguyện cộng đồng. Tăng 4 ĐRL tiêu chí 4.",
        eventType: "Thiện nguyện",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["thiện nguyện", "đrl", "hoạt động xã hội"],
        drlCriteria: 4,
        drlPoints: 4,
        hasSeating: false
    },
    {
        id: 31,
        type: "custom",
        image: "https://hiu.vn/wp-content/uploads/2023/03/DSC03048-800x285.jpg",
        title: "Hackathon AI HIU 2025",
        time: "2025-11-10 08:00",
        location: "HIU, TP.HCM",
        description: "Phát triển dự án AI. Tăng 5 ĐRL tiêu chí 3. Đăng ký ngay!",
        eventType: "Cuộc thi",
        audience: "Sinh viên CNTT",
        readMoreUrl: "#",
        tags: ["học tập", "cntt", "cuộc thi", "đrl"],
        drlCriteria: 3,
        drlPoints: 5,
        hasSeating: true
    },
    {
        id: 32,
        type: "custom",
        image: "https://images.unsplash.com/photo-1552581234-26160f608093",
        title: "Hội thảo Kỹ năng Thuyết trình",
        time: "2025-11-15 14:00",
        location: "HIU, TP.HCM",
        description:
            "Rèn kỹ năng thuyết trình. Tăng 3 ĐRL tiêu chí 2. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "kỹ năng", "đrl"],
        drlCriteria: 2,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 33,
        type: "custom",
        image:
            "https://hiu.vn/wp-content/uploads/2025/05/thum-ngay-hoi-quoc-te-dieu-duong-hiu-2025-800x285.jpg",
        title: "Hội thảo Python cho Người mới",
        time: "2025-11-20 10:00",
        location: "Online",
        description: "Học Python cơ bản. Tăng 3 ĐRL tiêu chí 3. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên CNTT",
        readMoreUrl: "#",
        tags: ["học tập", "cntt", "đrl"],
        drlCriteria: 3,
        drlPoints: 3,
        hasSeating: false
    },
    {
        id: 34,
        type: "custom",
        image: "https://images.unsplash.com/photo-1552581234-26160f608093",
        title: "Workshop Quản lý Thời gian",
        time: "2025-11-25 14:00",
        location: "HIU, TP.HCM",
        description:
            "Quản lý thời gian hiệu quả. Tăng 3 ĐRL tiêu chí 2. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "kỹ năng", "đrl"],
        drlCriteria: 2,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 35,
        type: "custom",
        image: "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f",
        title: "Cuộc thi Hùng biện Tiếng Anh",
        time: "2025-12-01 09:00",
        location: "HIU, TP.HCM",
        description: "Rèn kỹ năng hùng biện. Tăng 4 ĐRL tiêu chí 2. Đăng ký ngay!",
        eventType: "Cuộc thi",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "kỹ năng", "cuộc thi", "đrl"],
        drlCriteria: 2,
        drlPoints: 4,
        hasSeating: true
    },
    {
        id: 36,
        type: "custom",
        image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819",
        title: "Festival Âm nhạc HIU 2025",
        time: "2025-12-05 17:00",
        location: "Sân vận động HIU",
        description: "Thưởng thức âm nhạc sôi động. Tăng 2 ĐRL tiêu chí 2.",
        eventType: "Festival",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "festival", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: false
    },
    {
        id: 37,
        type: "custom",
        image: "https://images.unsplash.com/photo-1540575467063-1788fb27f5fb",
        title: "Ngày Hội Văn hóa Nhật Bản",
        time: "2025-12-10 09:00",
        location: "HIU, TP.HCM",
        description: "Khám phá văn hóa Nhật Bản. Tăng 2 ĐRL tiêu chí 2.",
        eventType: "Festival",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "festival", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 38,
        type: "custom",
        image: "https://images.unsplash.com/photo-1503676260728-332cceb654f3",
        title: "Ngày Hội Sách HIU",
        time: "2025-12-15 09:00",
        location: "Thư viện HIU",
        description:
            "Khám phá thế giới sách. Tăng 3 ĐRL tiêu chí 2. Tham gia ngay!",
        eventType: "Hoạt động đoàn thể",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "giải trí", "đrl"],
        drlCriteria: 2,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 39,
        type: "custom",
        image: "https://images.unsplash.com/photo-1552581234-26160f608093",
        title: "Talkshow Làm chủ Tài chính",
        time: "2025-12-20 14:00",
        location: "HIU, TP.HCM",
        description: "Học quản lý tài chính. Tăng 3 ĐRL tiêu chí 2. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "kỹ năng", "học bổng", "đrl"],
        drlCriteria: 2,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 40,
        type: "custom",
        image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655",
        title: "Hội thảo IELTS Band 7+",
        time: "2025-12-25 10:00",
        location: "Online",
        description:
            "Bí quyết đạt IELTS 7+. Tăng 3 ĐRL tiêu chí 2. Hỗ trợ học bổng!",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "học bổng", "kỹ năng", "đrl"],
        drlCriteria: 2,
        drlPoints: 3,
        hasSeating: false
    },
    {
        id: 41,
        type: "custom",
        image: "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f",
        title: "Hội thảo Blockchain và Tương Lai",
        time: "2025-11-02 14:00",
        location: "HIU, TP.HCM",
        description:
            "Khám phá công nghệ blockchain. Tăng 3 ĐRL tiêu chí 3. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên CNTT",
        readMoreUrl: "#",
        tags: ["học tập", "cntt", "đrl"],
        drlCriteria: 3,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 42,
        type: "custom",
        image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1",
        title: "Chiếu phim La La Land",
        time: "2025-11-04 18:00",
        location: "Hội trường HIU",
        description:
            "Thưởng thức phim tình cảm âm nhạc. Không ĐRL, chỉ để thư giãn!",
        eventType: "Chiếu phim",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "phim"],
        drlCriteria: 0,
        drlPoints: 0,
        hasSeating: true
    },
    {
        id: 43,
        type: "custom",
        image: "https://images.unsplash.com/photo-1556742524-750f2ab99913",
        title: "Hội thảo Y khoa: Sơ cứu Cộng đồng",
        time: "2025-11-06 09:00",
        location: "HIU, TP.HCM",
        description:
            "Học kỹ năng sơ cứu cơ bản. Tăng 3 ĐRL tiêu chí 4. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên Y khoa",
        readMoreUrl: "#",
        tags: ["học tập", "y khoa", "đrl"],
        drlCriteria: 4,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 44,
        type: "custom",
        image: "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f",
        title: "Cuộc thi Khởi nghiệp Kinh tế Xanh",
        time: "2025-11-08 08:00",
        location: "HIU, TP.HCM",
        description:
            "Ý tưởng kinh doanh bền vững. Tăng 5 ĐRL tiêu chí 3. Tham gia ngay!",
        eventType: "Cuộc thi",
        audience: "Sinh viên Kinh tế",
        readMoreUrl: "#",
        tags: ["học tập", "kinh tế", "cuộc thi", "khởi nghiệp", "đrl"],
        drlCriteria: 3,
        drlPoints: 5,
        hasSeating: true
    },
    {
        id: 45,
        type: "custom",
        image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819",
        title: "Ngày Hội Văn hóa Hàn Quốc",
        time: "2025-11-12 09:00",
        location: "HIU, TP.HCM",
        description: "Trải nghiệm văn hóa K-pop, ẩm thực. Không ĐRL, chỉ để vui!",
        eventType: "Festival",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "festival"],
        drlCriteria: 0,
        drlPoints: 0,
        hasSeating: true
    },
    {
        id: 46,
        type: "custom",
        image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655",
        title: "Hội thảo Học bổng Fulbright",
        time: "2025-11-14 14:00",
        location: "Online",
        description:
            "Tìm hiểu học bổng Fulbright. Tăng 3 ĐRL tiêu chí 1. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "học bổng", "đrl"],
        drlCriteria: 1,
        drlPoints: 3,
        hasSeating: false
    },
    {
        id: 47,
        type: "custom",
        image: "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f",
        title: "Hackathon Fintech HIU 2025",
        time: "2025-11-16 08:00",
        location: "HIU, TP.HCM",
        description:
            "Phát triển ứng dụng tài chính. Tăng 5 ĐRL tiêu chí 3. Đăng ký ngay!",
        eventType: "Cuộc thi",
        audience: "Sinh viên CNTT, Kinh tế",
        readMoreUrl: "#",
        tags: ["học tập", "cntt", "kinh tế", "cuộc thi", "đrl"],
        drlCriteria: 3,
        drlPoints: 5,
        hasSeating: true
    },
    {
        id: 48,
        type: "custom",
        image: "https://images.unsplash.com/photo-1502224562085-639556652f33",
        title: "Chiến dịch Trồng cây Xanh",
        time: "2025-11-18 07:00",
        location: "Công viên Gia Định, TP.HCM",
        description:
            "Trồng cây, bảo vệ môi trường. Tăng 4 ĐRL tiêu chí 4. Tham gia ngay!",
        eventType: "Thiện nguyện",
        audience: "Cộng đồng",
        readMoreUrl: "#",
        tags: ["thiện nguyện", "đrl", "hoạt động xã hội"],
        drlCriteria: 4,
        drlPoints: 4,
        hasSeating: false
    },
    {
        id: 49,
        type: "custom",
        image: "https://images.unsplash.com/photo-1536440136628-849c177e76a1",
        title: "Chiếu phim The Matrix",
        time: "2025-11-20 18:00",
        location: "Hội trường HIU",
        description: "Bom tấn khoa học viễn tưởng. Không ĐRL, chỉ để thư giãn!",
        eventType: "Chiếu phim",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "phim"],
        drlCriteria: 0,
        drlPoints: 0,
        hasSeating: true
    },
    {
        id: 50,
        type: "custom",
        image: "https://images.unsplash.com/photo-1552581234-26160f608093",
        title: "Hội thảo Kỹ năng Lãnh đạo",
        time: "2025-11-22 14:00",
        location: "HIU, TP.HCM",
        description:
            "Rèn kỹ năng lãnh đạo nhóm. Tăng 3 ĐRL tiêu chí 2. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "kỹ năng", "đrl"],
        drlCriteria: 2,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 51,
        type: "custom",
        image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819",
        title: "Festival Ẩm thực Quốc tế",
        time: "2025-11-24 10:00",
        location: "HIU, TP.HCM",
        description: "Thưởng thức ẩm thực toàn cầu. Không ĐRL, chỉ để vui!",
        eventType: "Festival",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "festival"],
        drlCriteria: 0,
        drlPoints: 0,
        hasSeating: true
    },
    {
        id: 52,
        type: "custom",
        image: "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f",
        title: "Cuộc thi Hùng biện Kinh tế",
        time: "2025-11-26 09:00",
        location: "HIU, TP.HCM",
        description:
            "Tranh luận về kinh tế số. Tăng 4 ĐRL tiêu chí 2. Đăng ký ngay!",
        eventType: "Cuộc thi",
        audience: "Sinh viên Kinh tế",
        readMoreUrl: "#",
        tags: ["học tập", "kinh tế", "cuộc thi", "đrl"],
        drlCriteria: 2,
        drlPoints: 4,
        hasSeating: true
    },
    {
        id: 53,
        type: "custom",
        image: "https://images.unsplash.com/photo-1576765607924-3a7bd1c73d84",
        title: "Ngày Hội Tình nguyện Đà Nẵng",
        time: "2025-11-28 08:00",
        location: "Đà Nẵng",
        description:
            "Hỗ trợ cộng đồng địa phương. Tăng 4 ĐRL tiêu chí 4. Tham gia ngay!",
        eventType: "Thiện nguyện",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["thiện nguyện", "đrl", "hoạt động xã hội"],
        drlCriteria: 4,
        drlPoints: 4,
        hasSeating: false
    },
    {
        id: 54,
        type: "custom",
        image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655",
        title: "Hội thảo Học bổng Erasmus",
        time: "2025-11-30 14:00",
        location: "Online",
        description:
            "Tìm hiểu học bổng Erasmus. Tăng 3 ĐRL tiêu chí 1. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên",
        readMoreUrl: "#",
        tags: ["học tập", "học bổng", "đrl"],
        drlCriteria: 1,
        drlPoints: 3,
        hasSeating: false
    },
    {
        id: 55,
        type: "custom",
        image: "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f",
        title: "Cuộc thi Thiết kế UI/UX",
        time: "2025-12-02 08:00",
        location: "HIU, TP.HCM",
        description:
            "Thiết kế giao diện ứng dụng. Tăng 5 ĐRL tiêu chí 3. Đăng ký ngay!",
        eventType: "Cuộc thi",
        audience: "Sinh viên CNTT",
        readMoreUrl: "#",
        tags: ["học tập", "cntt", "cuộc thi", "đrl"],
        drlCriteria: 3,
        drlPoints: 5,
        hasSeating: true
    },
    {
        id: 56,
        type: "custom",
        image: "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f",
        title: "Hội thảo Sức khỏe Tim mạch",
        time: "2025-12-04 14:00",
        location: "HIU, TP.HCM",
        description: "Hiểu biết về tim mạch. Không ĐRL, dành cho Y khoa!",
        eventType: "Hội thảo",
        audience: "Sinh viên Y khoa",
        readMoreUrl: "#",
        tags: ["học tập", "y khoa"],
        drlCriteria: 0,
        drlPoints: 0,
        hasSeating: true
    },
    {
        id: 57,
        type: "custom",
        image: "https://images.unsplash.com/photo-1540575467063-1788fb27f5fb",
        title: "Halloween Party HIU 2025",
        time: "2025-12-06 18:00",
        location: "Sân vận động HIU",
        description: "Tiệc hóa trang Halloween sôi động. Không ĐRL, chỉ để vui!",
        eventType: "Party",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "party"],
        drlCriteria: 0,
        drlPoints: 0,
        hasSeating: false
    },
    {
        id: 58,
        type: "custom",
        image: "https://images.unsplash.com/photo-1516321310766-61f6f7c0e96f",
        title: "Hội thảo Marketing Kỹ thuật số",
        time: "2025-12-08 14:00",
        location: "HIU, TP.HCM",
        description: "Học marketing online. Tăng 3 ĐRL tiêu chí 2. Đăng ký ngay!",
        eventType: "Hội thảo",
        audience: "Sinh viên Kinh tế",
        readMoreUrl: "#",
        tags: ["học tập", "kinh tế", "đrl"],
        drlCriteria: 2,
        drlPoints: 3,
        hasSeating: true
    },
    {
        id: 59,
        type: "custom",
        image: "https://images.unsplash.com/photo-1540575467063-1788fb27f5fb",
        title: "Ngày Hội Văn hóa Trung Quốc",
        time: "2025-12-12 09:00",
        location: "HIU, TP.HCM",
        description: "Khám phá văn hóa Trung Quốc. Tăng 2 ĐRL tiêu chí 2.",
        eventType: "Festival",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "festival", "đrl"],
        drlCriteria: 2,
        drlPoints: 2,
        hasSeating: true
    },
    {
        id: 60,
        type: "custom",
        image: "https://images.unsplash.com/photo-1540575467063-1788fb27f5fb",
        title: "Christmas Party HIU 2025",
        time: "2025-12-24 18:00",
        location: "Hội trường Beethoven, HIU",
        description: "Tiệc Giáng sinh ấm áp. Không ĐRL, chỉ để thư giãn!",
        eventType: "Party",
        audience: "Tất cả sinh viên",
        readMoreUrl: "#",
        tags: ["giải trí", "party"],
        drlCriteria: 0,
        drlPoints: 0,
        hasSeating: true
    }
];

export default events;
